### ISSUE TITLE
Scroll problems

### ISSUE THREAD

**Issue by AliceBBB** [dropways/deskapp#10]
Hi I'm italian so Sorry foto my English. I used deskapp to create my software but i see that scroll doesn't work by phone. The deskapp demo gave me the same problems, i Can scroll It touching the navbar on the right side, but i cant scroll the Page with my finger touch. What Can i do?
Thanks

**Comment by PierreGP** [comment]
Hi, same problem on Galaxy S6 & S7... We planned to use Deskapp as Mobile App template, so it won't be possible until a fix :)
Thx, awesome work guys !

**Comment by dropways** [comment]
Scroll problem solved in new commit.

Please pull new commit.

Thank you

**Comment by PierreGP** [comment]
Tested on my S7, sorry, does not solve 100% of the problem...
On the main dashboard for instance (index.php), the scroll starts only if I use 2 fingers (and I have "big" fingers :) )

++

**Comment by dot-brainy** [comment]
Same issue as @PierreGP

**Comment by dropways** [comment]
hi @PierreGP 

Can you please check latest commit in your device,

Please feel free to contribute.
Thank you

**Comment by AliceBBB** [comment]
It Is Better than before, but the problem isnt solved. Sometimes doesnt scroll, overall the sidebar.

Il 17 apr 2019 14:45, Ankit Hingarajiya <notifications@github.com> ha scritto:

hi @PierreGP<https://github.com/PierreGP>

Can you please check latest commit in your device,

Please feel free to contribute.
Thank you

**Comment by PierreGP** [comment]
Hi,
As said AliceBBB, it's better... even "much" better ! 
Unfortunately, I use Leaflfet to display interactive maps and there is a scroll problem too, I can't scroll/move my map.
